name: "Deploy to Netlify"

on:
  push:
    branches:
      - main
  workflow_dispatch::

  jobs:
    deploy:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout Repository
          uses: actions/checkout@v3
        - name: Install Netlify CLI
          run: npm install -g netlify-cli
        - name: Deploy to Netlify
          env:
            NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
            NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          run: netlify deploy --prod --dir=build --auth=$$NETLIFY_AUTH_TOKEN --site=$$NETLIFY_SITE_ID